### ISSUE TITLE
Request Add Features Upgrade and Escrow

### ISSUE THREAD

**Issue by GhostHackerData** [fauzymadani/AnonymousWebForum#2]

**Comment by hauraa2024** [comment]
the developmemt isb stopped bro

**Comment by hauraa2024** [comment]
> Thank you for create a new issue, your contributions is appreciated, happy coding!

the development is stopped bro, see `README.md`

**Comment by hauraa2024** [comment]
> _No description provided._

the development is stopped, maybe this project will archived by the author

**Comment by fauzymadani** [comment]
> _No description provided._

Thank you for opening a new issue, i appreciate it, but apparently, the development is stopped for some reason.
